XSkills.Web/Pages/Account/Admin.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;
using XSkills.Web.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using Serilog;
using Microsoft.EntityFrameworkCore;

namespace XSkills.Web.Pages.Account
{
    [Authorize(Roles = "superadmin,admin")]
    public class AdminModel : PageModel
    {
        private readonly UserManager<XSkillsUser> userManager;
        private readonly RoleManager<XSkillsRole> roleManager;
        private readonly XSkillsDbContext db;

        public AdminModel(UserManager<XSkillsUser> userManager, RoleManager<XSkillsRole> roleManager, SignInManager<XSkillsUser> signInManager, XSkillsDbContext db)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
            this.db = db;
        }

        public IEnumerable<UserFormModel> Users { get; set; }

        [BindProperty]
        public int UserId { get; set; }

        [BindProperty]
        public string Query { get; set; }

        public string Error { get; set; }

        public bool IsSuccess { get; set; }

        public async Task OnGetAsync()
        {
            await Initialize();
        }

        public async Task<IActionResult> OnPostAdminAsync()
        {
            var user = await GetUserAsync(UserId);
            if (user == null) return Redirect("/Account/LogOut");

            try
            {
                var roles = await userManager.GetRolesAsync(user);
                if (roles.Contains(MagicStrings.SuperAdmin) || !User.IsInRole(MagicStrings.SuperAdmin))
                {
                    Error = "You are not allowed to do that.";
                    await Initialize();
                    return Page();
                }
                else if (roles.Contains(MagicStrings.Admin))
                {
                    var result = await userManager.RemoveFromRoleAsync(user, MagicStrings.Admin);
                    IsSuccess = result.Succeeded;
                }
                else
                {
                    var result = await userManager.AddToRoleAsync(user, MagicStrings.Admin);
                    IsSuccess = result.Succeeded;
                }
            }
            catch(Exception ex)
            {
                Log.Error(ex, "Error occurred when granting admin rights");
            }

            await Initialize();
            if (!IsSuccess) Error = $"Role change failed for user {user.Email}.";
            return Page();
        }

        public async Task OnPostRemoveAsync()
        {
            var user = await GetUserAsync(UserId);
            if (user == null) return;

            var roles = await userManager.GetRolesAsync(user);
            if (roles.Any(x => x == MagicStrings.SuperAdmin || x == MagicStrings.Admin))
            {
                Error = "You cannot remove admin accounts.";
                await Initialize();
                return;
            }

            var result = await userManager.DeleteAsync(user);
            IsSuccess = result.Succeeded;
            if (!IsSuccess) Error = $"Could not delete user {user.Email}.";
            await Initialize();
        }

        public async Task<IActionResult> OnPostSuperAdminAsync()
        {
            var user = await GetUserAsync(UserId);
            if (user == null) return Page();
            var currentUser = await userManager.GetUserAsync(User);

            if (user.Id == currentUser.Id || !User.IsInRole(MagicStrings.SuperAdmin))
            {
                await Initialize();
                Error = "Something went wrong.";
                return Page();
            }

            var results = new List<IdentityResult>();
            try
            {
                if(await userManager.IsInRoleAsync(user, MagicStrings.Admin))
                    results.Add(await userManager.RemoveFromRoleAsync(user, MagicStrings.Admin));
                results.Add(await userManager.AddToRoleAsync(user, MagicStrings.SuperAdmin));
                results.Add(await userManager.AddToRoleAsync(currentUser, MagicStrings.Admin));
                results.Add(await userManager.RemoveFromRoleAsync(currentUser, MagicStrings.SuperAdmin));

                IsSuccess = results.All(x => x.Succeeded);
            }
            catch (Exception ex)
            {
                Log.Error(ex, "Error occurred when passing super admin rights");
                Error = $"Role change failed for user {user.Email}.";
                return Page();
            }

            if (!IsSuccess)
            {
                await Initialize();
                Error = string.Join(Environment.NewLine, results.Where(x => x != null && !x.Succeeded)
                    .Select(x => string.Join(Environment.NewLine, x.Errors.Select(y => y.Description))));
                return Page();
            }

            return Redirect("/Account/LogOut");
        }

        private async Task Initialize()
        {
            var adminRole = await roleManager.FindByNameAsync(MagicStrings.Admin);
            var superAdminRole = await roleManager.FindByNameAsync(MagicStrings.SuperAdmin);
            Users = from u in db.Users.Include(u => u.Employee)
                    join r in db.UserRoles on u.Id equals r.UserId into userRoles
                    from ur in userRoles.DefaultIfEmpty()
                    select UserFormModel.FromUser(u, ur.RoleId == superAdminRole.Id ? 2 : ur.RoleId == adminRole.Id ? 1 : 0);
        }

        private async Task<XSkillsUser> GetUserAsync(int id)
        {
            var user = await userManager.FindByIdAsync(UserId.ToString());
            if (user == null)
            {
                Error = "There is no such user.";
                await Initialize();
            }

            return user;
        }
    }
}

XSkills.Web/Pages/Account/ConfirmEmail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Identity;
using XSkills.Web.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace XSkills.Web.Pages.Account
{
    [AllowAnonymous]
    public class ConfirmEmailModel : PageModel
    {
        private readonly UserManager<XSkillsUser> userManager;
        private readonly XSkillsDbContext db;

        public ConfirmEmailModel(UserManager<XSkillsUser> userManager, XSkillsDbContext db)
        {
            this.userManager = userManager;
            this.db = db;
        }

        public List<string> Errors { get; set; } = new List<string>();

        public async Task<IActionResult> OnGet(string email, string token)
        {
            var user = await userManager.FindByEmailAsync(email);
            if (user != null)
            {
                var result = await userManager.ConfirmEmailAsync(user, token);
                if (result.Succeeded)
                {
                    user.Employee = new Employee { UserId = user.Id };
                    db.Employees.Add(user.Employee);
                    await db.SaveChangesAsync();
                    await userManager.AddClaimAsync(user, new Claim("employeeId", user.Employee.Id.ToString()));
                    return Page();
                }
                else
                {
                    Errors.AddRange(result.Errors.Select(x => x.Description));
                }
            }
            else
            {
                Errors.Add("Could not find that email.");
            }

            return Page();
        }
    }
}

XSkills.Web/Pages/Account/Edit.cshtml.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Identity;
using XSkills.Web.Models;
using XSkills.Web.Helpers;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using System;
using Serilog;
using Microsoft.AspNetCore.Http;
using System.IO;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Formats.Png;

namespace XSkills.Web.Pages.Account
{
    public class EditModel : PageModel
    {
        private readonly UserManager<XSkillsUser> userManager;
        private readonly SignInManager<XSkillsUser> signInManager;
        private readonly XSkillsDbContext db;

        [BindProperty(SupportsGet = true)]
        public ChangeNameFormModel NameForm { get; set; } = new ChangeNameFormModel();

        [BindProperty]
        public ChangePasswordFormModel PasswordForm { get; set; } = new ChangePasswordFormModel();

        [BindProperty(SupportsGet = true)]
        public ChangeEmailFormModel EmailForm { get; set; } = new ChangeEmailFormModel();

        [BindProperty]
        public int SelectedProjectId { get; set; }

        [BindProperty]
        public string Description { get; set; }

        public string Avatar { get; set; }

        public List<string> AvatarErrors { get; set; } = new List<string>();

        public List<Project> Projects { get; set; } = new List<Project>();

        public bool ShowAdminPanel { get; set; }

        public EditModel(UserManager<XSkillsUser> userManager, SignInManager<XSkillsUser> signInManager, XSkillsDbContext db)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.db = db;
        }

        public async void OnGetAsync()
        {
            var user = await userManager.GetUserAsync(User);
            await Initialize(user, null);
        }

        public async void OnPostName()
        {
            var user = await userManager.GetUserAsync(User);
            await Initialize(user, "name");

            this.ClearModelState();
            if (!ModelState.IsValid)
            {
                NameForm.Errors.AddRange(ModelState.SelectMany(e => e.Value.Errors.Select(x => x.ErrorMessage)));
                return;
            }

            user.FirstName = NameForm.FirstName;
            user.LastName = NameForm.LastName;
            var result = await userManager.UpdateAsync(user);
            if (result.Succeeded) NameForm.IsSuccess = true;
            else NameForm.Errors.AddRange(result.Errors.Select(x => x.Description));
        }

        public async void OnPostPassword()
        {
            var user = await userManager.GetUserAsync(User);
            await Initialize(user, null);

            this.ClearModelState();
            if (!ModelState.IsValid)
            {
                PasswordForm.Errors.AddRange(ModelState.SelectMany(e => e.Value.Errors.Select(x => x.ErrorMessage)));
                return;
            }

            var result = await userManager.ChangePasswordAsync(user, PasswordForm.OldPassword, PasswordForm.NewPassword);
            if (result.Succeeded) PasswordForm.IsSuccess = true;
            else PasswordForm.Errors.AddRange(result.Errors.Select(x => x.Description));
        }

        public async Task<IActionResult> OnPostEmail()
        {
            var user = await userManager.GetUserAsync(User);
            await Initialize(user, "email");

            this.ClearModelState();
            if (!ModelState.IsValid)
            {
                EmailForm.Errors.AddRange(ModelState.SelectMany(e => e.Value.Errors.Select(x => x.ErrorMessage)));
                return Page();
            }

            user.Email = EmailForm.Email;
            user.UserName = EmailForm.Email;
            var result = await userManager.UpdateAsync(user);

            if (result.Succeeded)
            {
                await signInManager.SignOutAsync();
                return Redirect("/Account/LogIn");
            }
            else
            {
                EmailForm.Errors.AddRange(result.Errors.Select(x => x.Description));
            }

            return Page();
        }

        public async void OnPostJoinProject()
        {
            try
            {
                var user = await userManager.GetUserAsync(User);
                db.UserToProjects.Add(new UserToProject { ProjectId = SelectedProjectId, UserId = user.Id });
                db.SaveChanges();
                await Initialize(user, null);
            }
            catch (Exception ex)
            {
                Log.Error(ex, "Failed to join project");
            }
        }

        public async void OnPostLeaveProject()
        {
            try
            {
                var user = await userManager.GetUserAsync(User);
                db.UserToProjects.Remove(db.UserToProjects.Single(x => x.ProjectId == SelectedProjectId && x.UserId == user.Id));
                db.SaveChanges();
                await Initialize(user, null);
            }
            catch (Exception ex)
            {
                Log.Error(ex, "Failed to leave project");
            }
        }

        public async void OnPostDescription()
        {
            try
            {
                var user = await userManager.GetUserAsync(User);
                user.Description = Description;
                await userManager.UpdateAsync(user);
                await Initialize(user, null);
            }
            catch (Exception ex)
            {
                Log.Error(ex, "Failed to update user profile");
            }
        }

        public async void OnPostAvatar(IFormFile avatar)
        {
            try
            {
                var user = await userManager.GetUserAsync(User);
                await Initialize(user, null);

                if (avatar == null)
                    AvatarErrors.Add("You need to choose a file.");

                if(!avatar?.ContentType.StartsWith("image") ?? false)
                    AvatarErrors.Add("You need to choose an image file.");

                if (avatar?.Length > 1024 * 1024)
                    AvatarErrors.Add("File size must be less than 1MB.");

                if (AvatarErrors.Any()) return;

                using (var stream = avatar.OpenReadStream())
                using (var outStream = new MemoryStream())
                using(var image = Image.Load(stream))
                {
                    image.Mutate(x => x.Resize(128, 128));
                    image.Save(outStream, new PngEncoder());
                    var buffer = new byte[outStream.Length];
                    outStream.Position = 0;
                    await outStream.ReadAsync(buffer, 0, (int)outStream.Length);
                    user.Avatar = Convert.ToBase64String(buffer);
                }

                db.Users.Update(user);
                db.SaveChanges();
                Avatar = user.Avatar;
            }
            catch(Exception ex)
            {
                AvatarErrors.Add("Something went wrong, please try again later.");
                Log.Error(ex, "Failed to set user avatar");
            }
        }

        private async Task Initialize(XSkillsUser user, string excludedAction)
        {
            if (excludedAction != "name") FillNameForm(user);
            if (excludedAction != "email") FillEmailForm(user);
            Description = user.Description;
            ShowAdminPanel = (await userManager.GetRolesAsync(user)).Any(x => x == MagicStrings.Admin || x == MagicStrings.SuperAdmin);
            Projects.AddRange(db.Projects.Include(x => x.UserToProjects));
            Avatar = user.Avatar;
        }

        private void FillNameForm(XSkillsUser user)
        {
            NameForm.FirstName = user.FirstName;
            NameForm.LastName = user.LastName;
        }

        private void FillEmailForm(XSkillsUser user) => EmailForm.Email = user.Email;
    }
}

XSkills.Web/Pages/Account/ForgotPassword.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Identity;
using XSkills.Web.Models;
using XSkills.Web.Services;
using Microsoft.Extensions.Options;
using System.ComponentModel.DataAnnotations;
using System.Web;
using Microsoft.AspNetCore.Authorization;

namespace XSkills.Web.Pages.Account
{
    [AllowAnonymous]
    public class ForgotPasswordModel : PageModel
    {
        private readonly UserManager<XSkillsUser> userManager;
        private readonly MailService mailService;
        private readonly IOptions<XSkillsConfig> config;

        public ForgotPasswordModel(UserManager<XSkillsUser> userManager, MailService mailService, IOptions<XSkillsConfig> config)
        {
            this.userManager = userManager;
            this.mailService = mailService;
            this.config = config;
        }

        [BindProperty]
        public ForgotPasswordFormModel Form { get; set; } = new ForgotPasswordFormModel();

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                Form.Errors.AddRange(ModelState.SelectMany(e => e.Value.Errors.Select(x => x.ErrorMessage)));
                return Page();
            }

            var user = await userManager.FindByEmailAsync(Form.Email);
            if (user != null)
            {
                string token = await userManager.GeneratePasswordResetTokenAsync(user);
                string url = $"{Request.Scheme}://{Request.Host.Value}/Account/ResetPassword?email={user.Email}&token={HttpUtility.UrlEncode(token)}";
                if(!mailService.SendEmail(user.Email, "Password reset", string.Format(config.Value.ResetPasswordEmailFormat, url)))
                {
                    Form.Errors.Add("An error occured when sending email.");
                    return Page();
                }
            }

            Form.IsSuccess = true;
            return Page();
        }
    }
}

XSkills.Web/Pages/Account/Admin.cshtml
@page
@using XSkills.Web.Models;
@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"
@model XSkills.Web.Pages.Account.AdminModel
@{
    int userId = int.Parse(User.Claims.FirstOrDefault(x => x.Type == System.Security.Claims.ClaimTypes.NameIdentifier).Value);
}
@functions
{
    public string GetAdminClass(int level)
    {
        switch (level)
        {
            case 2:
                return "is-danger";
            case 1:
                return "is-warning";
            default:
                return string.Empty;
        }
    }

    public string GetTimeDelta(DateTime skillUpdate)
    {
        var delta = DateTime.Now - skillUpdate;
        if (delta.TotalDays < 30) return $"{delta.Days} days ago";
        if (delta.TotalDays < 365) return $"{delta.Days / 30} months ago";
        return "More than a year ago";
    }
}
<div id="xskills">
    <nav class="navbar">
        <div class="container">
            <div class="navbar-brand">
                <a class="navbar-item">
                    <h1 class="title">XSkills</h1>
                </a>
                <button class="button navbar-burger" data-target="nav-menu">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
            </div>
            <div class="navbar-menu" id="nav-menu">
                <div class="navbar-end">
                    <div class="navbar-item">
                        <div class="field is-grouped">
                            <p class="control">
                                <a class="button is-white is-outlined" href="/">
                                    <span class="icon">
                                        <i class="fa fa-arrow-circle-left"></i>
                                    </span>
                                    <span>Home</span>
                                </a>
                            </p>
                            <p class="control">
                                <a href="/Account/Edit" class="button is-white is-outlined">
                                    <span class="icon">
                                        <i class="fa fa-address-card-o"></i>
                                    </span>
                                    <span>Profile</span>
                                </a>
                            </p>
                            <p class="control">
                                <a href="/Account/LogOut" class="button is-white is-outlined">
                                    <span class="icon">
                                        <i class="fa fa-sign-out"></i>
                                    </span>
                                    <span>Log out</span>
                                </a>
                            </p>
                            <div class="control has-icons-right">
                                <input asp-for="Query" class="input" placeholder="Filter by name..." type="text" v-model="query" />
                                <span class="icon is-small is-right">
                                    <i class="fa fa-filter"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="navbar-item">
                        <p>Hello, @User.Identity.Name</p>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <section class="section is-fullheight">
        <div class="container is-fullheight scroll-content">
            <h1 class="title">Manage users</h1>
            @if (Model.IsSuccess)
            {
                <div class="notification is-success">Success!</div>
            }

            @if (!string.IsNullOrEmpty(Model.Error))
            {
                <div class="notification is-danger">@Model.Error</div>
            }
            <div class="columns is-multiline">
                @foreach (var user in Model.Users)
                {
                    <div class="column is-6" v-if="matchesQuery('@user.FirstName @user.LastName')">
                        <div class="box">
                            <div class="level is-mobile">
                                <article class="media">
                                    <div class="media-left">
                                        <figure class="image is-64x64">
                                            <img src="@($"data:image/png;base64,{user.Avatar}")" alt="Image" />
                                        </figure>
                                    </div>
                                    <div class="media-content">
                                        <div class="content">
                                            <p>
                                                <strong>@user.FirstName @user.LastName</strong>
                                                <br /><small>@user.Email</small>
                                                <br /><small>Last update: @(user.LastSkillUpdate == null ? "NEVER" : $"{user.LastSkillUpdate.Value.ToShortDateString()} ({GetTimeDelta(user.LastSkillUpdate.Value)})")</small>
                                            </p>
                                        </div>
                                    </div>
                                </article>
                                <div>
                                    <div class="level field is-grouped">
                                        @if (User.IsInRole(XSkills.Web.MagicStrings.SuperAdmin) && user.Id != userId)
                                        {
                                            <form method="post" asp-page-handler="superAdmin" class="level-item">
                                                <p class="control">
                                                    <input type="hidden" asp-for="UserId" value="@user.Id" />
                                                    <button type="submit" class="button is-white is-outlined">
                                                        <span class="icon"><i class="fa fa-star"></i></span>
                                                    </button>
                                                </p>
                                            </form>
                                        }
                                        <form method="post" asp-page-handler="admin" class="level-item">
                                            <p class="control">
                                                <input type="hidden" asp-for="UserId" value="@user.Id" />
                                                <button type="submit" class="button is-white is-outlined @{ Write(GetAdminClass(user.AdminLevel)); }">
                                                    @if (user.AdminLevel > 0)
                                                    {
                                                        <span class="icon"><i class="fa fa-toggle-on"></i></span>
                                                    }
                                                    else
                                                    {
                                                        <span class="icon"><i class="fa fa-toggle-off"></i></span>
                                                    }
                                                </button>
                                            </p>
                                        </form>
                                        <form method="post" asp-page-handler="remove" id="delete-@user.Id" class="level-item">
                                            <p class="control">
                                                <input type="hidden" asp-for="UserId" value="@user.Id" />
                                                <a v-on:click="confirmDelete('@user.FirstName @user.LastName', @user.Id)" class="button is-white is-outlined">
                                                    <span class="icon"><i class="fa fa-user-times"></i></span>
                                                </a>
                                            </p>
                                        </form>
                                    </div>
                                    <p class="control">
                                        <div class="select">
                                            <select id="status-@user.Id" v-on:change="setAssignmentStatus(@user.Id)">
                                                <option value="0" selected="@(AssignmentStatus.Unknown == user.AssignmentStatus)">Unknown</option>
                                                <option value="1" selected="@(AssignmentStatus.Unassigned == user.AssignmentStatus)">Unassigned</option>
                                                <option value="2" selected="@(AssignmentStatus.Internal == user.AssignmentStatus)">Internal</option>
                                                <option value="3" selected="@(AssignmentStatus.CommercialNotMonetized == user.AssignmentStatus)">Commercial (not monetized)</option>
                                                <option value="4" selected="@(AssignmentStatus.Commercial == user.AssignmentStatus)">Commercial</option>
                                            </select>
                                        </div>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
        <div class="modal is-active" v-if="showDeletePopup">
            <div class="modal-background"></div>
            <div class="modal-card">
                <header class="modal-card-head">
                    <p class="modal-card-title">Confirm user deletion</p>
                    <button class="delete" aria-label="close" v-on:click="hidePopup()"></button>
                </header>
                <section class="modal-card-body">
                    <p>Are you sure to delete {{name}}?</p>
                </section>
                <footer class="modal-card-foot">
                    <button class="button is-success" v-on:click="deleteUser(id)">Delete</button>
                    <button class="button" v-on:click="hidePopup()">Close</button>
                </footer>
            </div>
        </div>
    </section>
    @Html.Partial("~/Components/Footer.cshtml")
</div>
<script type="text/javascript">
    var vue = new Vue({
        el: '#xskills',
        data: {
            query: '@Model.Query',
            showDeletePopup: false,
            name: '',
            id: 0
        },
        methods: {
            matchesQuery: function (name) {
                return name.toLowerCase().indexOf(this.query.toLowerCase()) !== -1;
            },
            confirmDelete: function (name, id) {
                this.id = id;
                this.name = name;
                this.showDeletePopup = true;
            },
            deleteUser: function () {
                var form = document.getElementById('delete-' + this.id);
                form.submit();
                this.hidePopup();
            },
            hidePopup: function () {
                this.showDeletePopup = false;
                this.id = 0;
                this.name = '';
            },
            setAssignmentStatus: function (id) {
                var elem = document.getElementById('status-' + id);
                var value = elem.value;
                elem.parentElement.setAttribute('class', 'select');
                fetch('/api/Employees/SetAssignmentStatus?id=' + id + '&assignmentStatus=' + value, {
                    method: 'GET', credentials: 'include'
                }).then(r => {
                    if (r.ok) elem.parentElement.setAttribute('class', 'select is-success');
                    else elem.parentElement.setAttribute('class', 'select is-danger');
                });
            }
        }
    });
</script>

XSkills.Web/Pages/Account/ConfirmEmail.cshtml
@page
@model XSkills.Web.Pages.Account.ConfirmEmailModel
<div id="xskills">
    <section class="section has-text-centered">
        <div class="is-fullheight vertical-center">
            @if (!Model.Errors.Any())
            {
                <h1 class="title">Email confirmed</h1>
                <p>You can now <a href="/Account/LogIn">log in</a>.</p>
            }
            else
            {
                @foreach(var error in Model.Errors)
                {
                    <div class="notification is-danger">@error</div>
                }
            }
        </div>
    </section>
    @Html.Partial("~/Components/Footer.cshtml")
</div>

XSkills.Web/Pages/Account/LogOut.cshtml
@page
@model XSkills.Web.Pages.Account.LogOutModel