XSkills.Web/Models/Project.cs
using System.Collections.Generic;

namespace XSkills.Web.Models
{
    public class Project : NamedEntity
    {
        public Project()
        {
            UserToProjects = new List<UserToProject>();
            TagToProjects = new List<TagToProject>();
        }

        public bool IsRetired { get; set; }

        public string Description { get; set; }

        public string LiveUrl { get; set; }

        public List<UserToProject> UserToProjects { get; set; }

        public List<TagToProject> TagToProjects { get; set; }
    }
}

XSkills.Web/Pages/Analytics.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using XSkills.Web.Models;
using XSkills.Web.Services;

namespace XSkills.Web.Pages
{
    public class AnalyticsModel : PageModel
    {
        private readonly XSkillsDbContext db;
        private readonly AnalyticsService<XSkillsDbContext> analyticsService;

        public AnalyticsModel(XSkillsDbContext db, AnalyticsService<XSkillsDbContext> analyticsService)
        {
            this.db = db;
            this.analyticsService = analyticsService;
        }

        public List<AnalyticsMapInfo> AnalyticsTypes { get; set; }

        public Dictionary<int, string> Skills { get; set; }

        [BindProperty]
        public string SelectedAnalytics { get; set; }

        [BindProperty]
        public string SelectedSkills { get; set; }

        [BindProperty]
        public int SelectedLevel { get; set; }

        public Dictionary<string, string> DataSingle { get; set; }

        public Dictionary<string, IEnumerable<string>> DataCollection { get; set; }

        public Dictionary<AssignmentStatus, IEnumerable<NamedEmployee>> Employees { get; set; }

        public AnalyticsDefinition Analytics { get; set; }

        public void OnGet()
        {
            Initialize();
            SelectedAnalytics = AnalyticsTypes.FirstOrDefault()?.Name;
        }

        public void OnPostAnalytics()
        {
            Initialize();
            Analytics = analyticsService.GetMap(SelectedAnalytics);
            DataSingle = Analytics.EvaluateSingle(db);
            DataCollection = Analytics.EvaluateCollection(db);
        }

        public void OnPostCompetences()
        {
            Initialize();
            var selectedSkills = SelectedSkills.Split(',', System.StringSplitOptions.RemoveEmptyEntries).Select(x => int.Parse(x));
            Employees = db.Employees.Include(x => x.Skills).ThenInclude(x => x.Skill).Include(x => x.User)
                .Where(x => x.Skills.Any(y => selectedSkills.Contains(y.SkillId) && y.ProficiencyLevel >= SelectedLevel)).ToList()
                .GroupBy(x => x.User.AssignmentStatus).OrderBy(x => x.Key)
                .ToDictionary(x => x.Key, x => x.Select(y => NamedEmployee.FromEmployee(y)));

            foreach(var group in Employees)
            {
                foreach(var item in group.Value)
                {
                    item.Skills.RemoveAll(x => !selectedSkills.Contains(x.SkillId));
                }
            }
        }

        private void Initialize()
        {
            AnalyticsTypes = analyticsService.GetMapsInfo().ToList();
            Skills = db.Skills.OrderBy(x => x.Name).ToDictionary(x => x.Id, x => x.Name);
        }
    }
}

XSkills.Web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;

namespace XSkills.Web.Pages
{
    [AllowAnonymous]
    public class ErrorModel : PageModel
    {
        public string ErrorMessage { get; set; }

        public void OnGet(int? statusCode)
        {
            switch(statusCode)
            {
                case 404:
                    ErrorMessage = "The requested page could not be found.";
                    break;
                case 500:
                    ErrorMessage = "Server error occured. Go tell your admin to check the logs.";
                    break;
                case null:
                default:
                    ErrorMessage = "Something went wrong.";
                    break;
            }
        }
    }
}

XSkills.Web/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace XSkills.Web.Pages
{
    public class IndexModel : PageModel { }
}

XSkills.Web/Pages/Profile.cshtml.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using XSkills.Web.Models;
using Microsoft.EntityFrameworkCore;

namespace XSkills.Web.Pages
{
    public class ProfileModel : PageModel
    {
        private readonly XSkillsDbContext db;

        public XSkillsUser CurrentUser { get; private set; }

        public ProfileModel(XSkillsDbContext db)
        {
            this.db = db;
        }

        public IActionResult OnGet(int id)
        {
            CurrentUser = db.Users.Include(x => x.UserToProjects).ThenInclude(x => x.Project)
                .Include(x => x.Employee).ThenInclude(x => x.Skills).ThenInclude(x => x.Skill).ThenInclude(x => x.SkillGroup).FirstOrDefault(x => x.Id == id);
            if (CurrentUser == null) return NotFound();
            return Page();
        }
    }
}

XSkills.Web/Pages/Project.cshtml.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc.RazorPages;
using XSkills.Web.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;

namespace XSkills.Web.Pages
{
    public class ProjectModel : PageModel
    {
        private readonly XSkillsDbContext db;

        public ProjectModel(XSkillsDbContext db)
        {
            this.db = db;
        }

        public Project Project { get; set; }

        public IActionResult OnGet(int id)
        {
            Project = db.Projects
                .Include(x => x.TagToProjects).ThenInclude(x => x.Tag)
                .Include(x => x.UserToProjects).ThenInclude(x => x.User)
                .SingleOrDefault(x => x.Id == id);
            if (Project == null) return NotFound();
            return Page();
        }
    }
}

XSkills.Web/Pages/Projects.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using XSkills.Web.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using XSkills.Web.Helpers;
using Serilog;

namespace XSkills.Web.Pages
{
    [Authorize(Roles = "superadmin,admin")]
    public class ProjectsModel : PageModel
    {
        private readonly XSkillsDbContext db;

        public ProjectsModel(XSkillsDbContext db)
        {
            this.db = db;
        }

        [BindProperty]
        public int SelectedProjectId { get; set; }

        public List<SelectProjectFormModel> Projects { get; } = new List<SelectProjectFormModel>();

        public List<Tag> Tags { get; set; } = new List<Tag>();

        [BindProperty]
        public ProjectFormModel CurrentProject { get; set; } = new ProjectFormModel();

        public void OnGet() => Initialize();

        public void OnPostSelect()
        {
            Initialize();
            var project = db.Projects.Include(x => x.TagToProjects).FirstOrDefault(x => x.Id == SelectedProjectId);
            if (project != null)
            {
                CurrentProject = new ProjectFormModel
                {
                    Id = project.Id,
                    Name = project.Name,
                    Description = project.Description,
                    Tags = project.TagToProjects,
                    IsRetired = project.IsRetired,
                    LiveUrl = project.LiveUrl
                };
            }
        }

        public void OnPostProject()
        {
            this.ClearModelState();
            if(!ModelState.IsValid)
            {
                CurrentProject.Errors.AddRange(ModelState.SelectMany(e => e.Value.Errors.Select(x => x.ErrorMessage)));
                Initialize();
                return;
            }

            var project = new Project
            {
                Id = CurrentProject.Id,
                Name = CurrentProject.Name,
                Description = CurrentProject.Description,
                IsRetired = CurrentProject.IsRetired,
                LiveUrl = CurrentProject.LiveUrl
            };

            if (CurrentProject.Id == 0)
            {
                db.Projects.Add(project);
            }
            else
            {
                db.Projects.Update(project);
            }

            try
            {
                db.SaveChanges();
                CurrentProject = new ProjectFormModel
                {
                    Id = project.Id,
                    Name = project.Name,
                    Description = project.Description,
                    IsRetired = project.IsRetired,
                    LiveUrl = project.LiveUrl
                };
            }
            catch (Exception ex)
            {
                Log.Error(ex, "Saving project failed");
                CurrentProject.Errors.Add("Could not update the project.");
            }

            Initialize();
        }

        private void Initialize()
        {
            Projects.AddRange(db.Projects.Select(x => new SelectProjectFormModel
            {
                Id = x.Id,
                Name = x.Name,
                IsRetired = x.IsRetired
            }).ToList());

            Tags.AddRange(db.Tags);
        }
    }
}

XSkills.Web/Pages/UserReport.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using XSkills.Web.Models;

namespace XSkills.Web.Pages
{
    public class UserReportModel : PageModel
    {
        private readonly XSkillsDbContext db;

        public List<XSkillsUser> Users { get; set; }

        public UserReportModel(XSkillsDbContext db)
        {
            this.db = db;
        }

        public IActionResult OnGet(string userIds)
        {
            try
            {
                var ids = userIds.Split(',', StringSplitOptions.RemoveEmptyEntries).Select(x => int.Parse(x));
                Users = db.Users.Include(x => x.UserToProjects).ThenInclude(x => x.Project)
                .Include(x => x.Employee).ThenInclude(x => x.Skills).ThenInclude(x => x.Skill).ThenInclude(x => x.SkillGroup)
                .Where(x => ids.Contains(x.Id)).ToList();
            }
            catch (Exception ex)
            {
                return Redirect("/Error/500");
            }

            return Page();
        }
    }
}

XSkills.Web/Pages/Index.cshtml
@page
@{
    string employeeId = User.Claims.Single(x => x.Type == "employeeId").Value;
}

<div id="xskills">
    <nav class="navbar">
        <div class="container">
            <div class="navbar-brand">
                <a class="navbar-item">
                    <h1 class="title">XSkills</h1>
                </a>
                <button class="button navbar-burger" data-target="nav-menu">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
            </div>
            <div class="navbar-menu" id="nav-menu">
                <div class="navbar-end">
                    <div class="navbar-item">
                        <div class="field is-grouped">
                            <p class="control">
                                <a class="button is-white is-outlined" v-on:click="currentState = displayState.search">
                                    <span class="icon">
                                        <i class="fa fa-search"></i>
                                    </span>
                                    <span>Search</span>
                                </a>
                            </p>
                            <p class="control">
                                <a class="button is-white is-outlined" v-on:click="currentState = displayState.manage">
                                    <span class="icon">
                                        <i class="fa fa-cogs"></i>
                                    </span>
                                    <span>Manage</span>
                                </a>
                            </p>
                            <p class="control">
                                <a class="button is-white is-outlined" href="/Analytics">
                                    <span class="icon">
                                        <i class="fa fa-pie-chart"></i>
                                    </span>
                                    <span>Analytics</span>
                                </a>
                            </p>
                        </div>
                    </div>
                    <div class="navbar-item">
                        <div class="field is-grouped">
                            <p class="control">
                                <a class="button is-white is-outlined" v-on:click="selectEmployee('@employeeId')">
                                    <span class="icon">
                                        <i class="fa fa-user"></i>
                                    </span>
                                    <span>Your skills</span>
                                </a>
                            </p>
                            <p class="control">
                                <a href="/Account/Edit" class="button is-white is-outlined">
                                    <span class="icon">
                                        <i class="fa fa-address-card-o"></i>
                                    </span>
                                    <span>Profile</span>
                                </a>
                            </p>
                            <p class="control">
                                <a href="/Account/LogOut" class="button is-white is-outlined">
                                    <span class="icon">
                                        <i class="fa fa-sign-out"></i>
                                    </span>
                                    <span>Log out</span>
                                </a>
                            </p>
                        </div>
                    </div>
                    <div class="navbar-item">
                        <p>Hello, @User.Identity.Name</p>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <div class="is-fullheight has-text-centered vertical-center" v-if="currentState === displayState.loading">
        <p><i class="fa fa-cog fa-spin fa-5x fa-fw"></i></p>
    </div>
    <xskills-search v-on:employeeselected="selectEmployee" v-if="currentState === displayState.search"></xskills-search>
    <xskills-manage v-if="currentState === displayState.manage"></xskills-manage>
    <xskills-editemployee v-if="currentState === displayState.editEmployee" :employee="currentEmployee"></xskills-editemployee>
    @Html.Partial("~/Components/Footer.cshtml")
</div>
@Html.Partial("~/Components/Search.cshtml")
@Html.Partial("~/Components/Manage.cshtml")
@Html.Partial("~/Components/EditEmployee.cshtml")
<script>
    var v = new Vue({
        el: '#xskills',
        data: {
            currentEmployee: null,
            displayState: { search: 'search', manage: 'manage', editEmployee: 'editEmployee', loading: 'loading' },
            currentState: 'search'
        },
        methods: {
            selectEmployee: function (id) {
                var t = this;
                t.currentState = t.displayState.loading;
                fetch('/api/Employees/' + id, { method: 'GET', credentials: 'include' })
                    .then(r => {
                        if (r.ok) return r.json();
                        t.currentState = t.displayState.search;
                    }).then(d => {
                        if (d) {
                            for (s of d.skills) s.showTags = false;
                            t.currentEmployee = d;
                            t.currentState = t.displayState.editEmployee;
                        }
                    });
            }
        }
    });
</script>

XSkills.Web/Pages/Profile.cshtml
@page "{id}"
@model XSkills.Web.Pages.ProfileModel
@section headAddons {
    <script type="text/javascript" src="~/js/marked.min.js"></script>
}

<div id="xskills">
    <nav class="navbar">
        <div class="container">
            <div class="navbar-brand">
                <a class="navbar-item">
                    <h1 class="title">XSkills</h1>
                </a>
                <button class="button navbar-burger" data-target="nav-menu">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
            </div>
            <div class="navbar-menu" id="nav-menu">
                <div class="navbar-end">
                    <div class="navbar-item">
                        <div class="field is-grouped">
                            <p class="control">
                                <a class="button is-white is-outlined" href="/">
                                    <span class="icon">
                                        <i class="fa fa-arrow-circle-left"></i>
                                    </span>
                                    <span>Home</span>
                                </a>
                            </p>
                            <p class="control">
                                <a href="/Account/LogOut" class="button is-white is-outlined">
                                    <span class="icon">
                                        <i class="fa fa-sign-out"></i>
                                    </span>
                                    <span>Log out</span>
                                </a>
                            </p>
                        </div>
                    </div>
                    <div class="navbar-item">
                        <p>Hello, @User.Identity.Name</p>
                    </div>
                </div>
            </div>
        </div>
    </nav>

    @Html.Partial("~/Partials/UserProfile.cshtml", (Model.CurrentUser, false))

    @Html.Partial("~/Components/Footer.cshtml")
</div>

XSkills.Web/Pages/Projects.cshtml
@page
@model XSkills.Web.Pages.ProjectsModel
@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"

<div id="xskills">
    <nav class="navbar">
        <div class="container">
            <div class="navbar-brand">
                <a class="navbar-item">
                    <h1 class="title">XSkills</h1>
                </a>
                <button class="button navbar-burger" data-target="nav-menu">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
            </div>
            <div class="navbar-menu" id="nav-menu">
                <div class="navbar-end">
                    <div class="navbar-item">
                        <div class="field is-grouped">
                            <p class="control">
                                <a class="button is-white is-outlined" href="/">
                                    <span class="icon">
                                        <i class="fa fa-arrow-circle-left"></i>
                                    </span>
                                    <span>Home</span>
                                </a>
                            </p>
                            <p class="control">
                                <a href="/Account/Edit" class="button is-white is-outlined">
                                    <span class="icon">
                                        <i class="fa fa-address-card-o"></i>
                                    </span>
                                    <span>Profile</span>
                                </a>
                            </p>
                            <p class="control">
                                <a href="/Account/LogOut" class="button is-white is-outlined">
                                    <span class="icon">
                                        <i class="fa fa-sign-out"></i>
                                    </span>
                                    <span>Log out</span>
                                </a>
                            </p>
                        </div>
                    </div>
                    <div class="navbar-item">
                        <p>Hello, @User.Identity.Name</p>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <section class="section is-fullheight">
        <div class="container is-fullheight">
            <div class="columns is-fullheight">
                <div class="column is-3">
                    <h2 class="subtitle">Select project</h2>
                    <form method="post" asp-page-handler="Select">
                        <div class="field">
                            <div class="control">
                                <div class="select is-fullwidth">
                                    <select asp-for="SelectedProjectId">
                                        @foreach (var project in Model.Projects)
                                        {
                                            <option value="@project.Id">@project.Name</option>
                                        }
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="field has-addons">
                            <p class="control is-fullwidth">
                                <button type="submit" class="button is-white is-outlined is-fullwidth">Show</button>
                            </p>
                            <p class="control is-fullwidth">
                                <a href="/Projects" class="button is-white is-outlined is-fullwidth">Clear</a>
                            </p>
                        </div>
                    </form>
                    @if (Model.CurrentProject.Id != 0)
                    {
                        <div class="field">
                            <label class="label">Project tags</label>
                            <div class="control">
                                <input class="input" type="text" v-model="tagQuery">
                            </div>
                        </div>
                        <div class="tags">
                            <span class="tag" v-for="t in tags" v-if="!t.isSelected && tagQuery && t.name.toLowerCase().indexOf(tagQuery.toLowerCase()) > -1" v-on:click="tag(t)">{{t.name}}</span>
                        </div>
                    }
                </div>
                <div class="column is-9 is-fullheight scroll-content">
                    <div class="columns is-fullheight">
                        <div class="column is-half">
                            <form asp-page-handler="Project" method="post">
                                <input type="hidden" asp-for="CurrentProject.Id"/>
                                <div class="field">
                                    <div class="control is-fullwidth">
                                        <label asp-for="CurrentProject.Name" class="label">Project name</label>
                                        <input v-model="projectName" class="input" type="text" asp-for="CurrentProject.Name" maxlength="30">
                                    </div>
                                    <div class="control is-fullwidth">
                                        <label asp-for="CurrentProject.Description" class="label">Project description</label>
                                        <textarea v-model="projectDescription" asp-for="CurrentProject.Description" class="textarea" rows="10"></textarea>
                                    </div>
                                </div>
                                <div class="field">
                                    <label asp-for="CurrentProject.LiveUrl" class="label">Live url</label>
                                    <input type="text" asp-for="CurrentProject.LiveUrl" class="input" v-model="liveUrl"/>
                                </div>
                                <label class="checkbox">
                                    <input type="checkbox" asp-for="CurrentProject.IsRetired"/>
                                    Retired project
                                </label>
                                <button type="submit" class="button is-white is-outlined is-fullwidth">@(Model.CurrentProject.Id == 0 ? "Create" : "Update")</button>
                                <p>Supports <a href="https://daringfireball.net/projects/markdown/syntax" target="_blank">Markdown</a>.</p>
                                @foreach (var error in Model.CurrentProject.Errors)
                                {
                                    <div class="notification is-danger">@error</div>
                                }
                            </form>
                            <div class="tags" style="margin-top: 10px;">
                                <span class="tag is-medium" v-for="t in tags" v-if="t.isSelected">{{t.name}}<button class="delete" v-on:click="untag(t)"></button></span>
                            </div>
                        </div>
                        <div class="column is-half">
                            <h1 class="title">{{projectName}}</h1>
                            <a v-bind:href="liveUrl" v-if="liveUrl && liveUrl != ''">{{liveUrl}}</a>
                            <div v-html="markdown" class="content"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    @Html.Partial("~/Components/Footer.cshtml")
</div>
<script type="text/javascript" src="~/js/marked.min.js"></script>
<script type="text/javascript">
    var vue = new Vue({
        el: '#xskills',
        data: {
            projectName: '@Html.Raw(Model.CurrentProject?.Name?.Replace("'", "\\'"))',
            projectDescription: `@Html.Raw(Model.CurrentProject?.Description?.Replace("'", "\\'").Replace("`", "\\`"))`,
            liveUrl: '@Model.CurrentProject.LiveUrl',
            tagQuery: '',
            tags: [ @Html.Raw(string.Join(", ", Model.Tags.Select(x => $"{{ name: '{x.Name}', id: '{x.Id}', isSelected: {Model.CurrentProject.Tags?.Any(y => y.TagId == x.Id).ToString().ToLower() ?? "false"} }}"))) ]
        },
        computed: {
            markdown: function () {
                return marked(this.projectDescription, { sanitize: true });
            }
        },
        methods: {
            tag: function (tag) {
                var t = this;
                fetch('/api/Projects/Tag/@(Model.CurrentProject.Id)/' + tag.id, {
                    credentials: 'include',
                    method: 'GET'
                }).then(r => {
                    return r.json().then(d => {
                        if (r.ok) {
                            tag.isSelected = true;
                        }
                    });
                });
            },
            untag: function (tag) {
                var t = this;
                fetch('/api/Projects/Untag/@(Model.CurrentProject.Id)/' + tag.id, {
                    credentials: 'include',
                    method: 'GET'
                }).then(r => {
                    return r.json().then(d => {
                        if (r.ok) {
                            tag.isSelected = false;
                        }
                    });
                });
            }
        }
    });
</script>

XSkills.Web/Pages/UserReport.cshtml
@page
@model XSkills.Web.Pages.UserReportModel
@section headAddons {
    <script type="text/javascript" src="~/js/marked.min.js"></script>
}

@section styleOverride {
    <link rel="stylesheet" href="~/css/bulma.min.css" />
}
<section class="section is-fullheight scroll-content">
    @foreach (var item in Model.Users)
    {
        Html.RenderPartial("~/Partials/UserProfile.cshtml", (item, true));
    }
</section>

XSkills.Web/Pages/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>XSkills</title>
    @if (!IsSectionDefined("styleOverride"))
    {
        <link rel="stylesheet" href="~/css/bulmaswatch.min.css" />
    }
    else
    {
        @RenderSection("styleOverride", required: false)
    }
    <link rel="stylesheet" href="~/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("headAddons", required: false)
    <script type="text/javascript" src="~/js/vue.js"></script>
</head>
<body>
    @RenderBody()
    <script type="text/javascript">
        document.addEventListener('DOMContentLoaded', function () {
            var $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);
            if ($navbarBurgers.length > 0) {
                $navbarBurgers.forEach(function ($el) {
                    $el.addEventListener('click', function () {
                        var target = $el.dataset.target;
                        var $target = document.getElementById(target);
                        $el.classList.toggle('is-active');
                        $target.classList.toggle('is-active');
                    });
                });
            }
        });
    </script>
</body>
</html>